In [2]:
import pandas as pd
import os

In [2]:
def conv_to_mseconds(str):
    if str[-2:] == 'ms':
        return float(str[:-2]) 
    elif str[-2:] == 'µs':
        return float(str[:-2]) / 1000
    elif str[-2:] == '0s':
        return float(str[:-1])

path = 'intermedia_CSV_files/'
csv_files = [file for file in os.listdir(path) if file.endswith('.csv')]

for csv_file in csv_files:
    df = pd.read_csv(os.path.join(path, csv_file))

    df['time'] = df['time'].apply(conv_to_mseconds)
    df.to_csv(os.path.join(path, csv_file), index=False)

In [3]:
# Укажите путь к папке с CSV файлами
folder_path = 'intermedia_CSV_files/'

# Список для хранения всех отдельных DataFrame
data_frames = []

# Перебор всех файлов в папке
for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)
        # Чтение CSV файла и добавление его в список
        df = pd.read_csv(file_path)
        data_frames.append(df)

# Объединение всех DataFrame в один
combined_df = pd.concat(data_frames, ignore_index=True)

# Сохранение объединенного DataFrame в новый CSV файл
combined_df.to_csv('all_test.csv', index=False)

In [3]:
df = pd.read_csv('all_test.csv')
df

         paradigm start_combination func      time   system  start_property
0      functional           P,W,R,O    P  0.197468    linux               0
1      functional           P,W,R,O    W  1.155801    linux               0
2      functional           P,W,R,O    R  0.083870    linux               0
3      functional           P,W,R,O    O  0.243696    linux               0
4      functional           P,W,O,R    P  0.077298    linux               0
...           ...               ...  ...       ...      ...             ...
1147  objectively           W,P,O,R    R  1.119100  windows               1
1148  objectively           W,P,R,O    W  1.669700  windows               1
1149  objectively           W,P,R,O    P  1.095200  windows               1
1150  objectively           W,P,R,O    R  2.121900  windows               1
1151  objectively           W,P,R,O    O  1.017800  windows               1

[1152 rows x 6 columns]